# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PruebaVideo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PruebaVideo(object):
    def setupUi(self, PruebaVideo):
        PruebaVideo.setObjectName("PruebaVideo")
        PruebaVideo.resize(640, 480)
        PruebaVideo.setMinimumSize(QtCore.QSize(640, 480))
        PruebaVideo.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(PruebaVideo)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.label.setMinimumSize(QtCore.QSize(640, 480))
        self.label.setMaximumSize(QtCore.QSize(640, 480))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        PruebaVideo.setCentralWidget(self.centralwidget)

        self.retranslateUi(PruebaVideo)
        QtCore.QMetaObject.connectSlotsByName(PruebaVideo)

    def retranslateUi(self, PruebaVideo):
        _translate = QtCore.QCoreApplication.translate
        PruebaVideo.setWindowTitle(_translate("PruebaVideo", "Prueba de Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PruebaVideo = QtWidgets.QMainWindow()
    ui = Ui_PruebaVideo()
    ui.setupUi(PruebaVideo)
    PruebaVideo.show()
    sys.exit(app.exec_())
